# Generated by Django 3.2.9 on 2022-02-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Andraikitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andraikitra', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Andraikitra',
            },
        ),
        migrations.CreateModel(
            name='Apv',
            fields=[
                ('apv', models.IntegerField(primary_key=True, serialize=False)),
                ('mpiaro', models.CharField(max_length=50)),
                ('fankalazana', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Apv',
            },
        ),
        migrations.CreateModel(
            name='Bordereau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numero', models.IntegerField()),
                ('ligne', models.IntegerField()),
                ('verse_par', models.CharField(max_length=50)),
                ('recu_par', models.CharField(max_length=50)),
                ('taona', models.IntegerField()),
                ('hasina', models.IntegerField()),
                ('seminera', models.IntegerField()),
                ('diosezy', models.IntegerField()),
                ('marina', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Bordereaux',
            },
        ),
        migrations.CreateModel(
            name='Fikambanana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sokajy', models.CharField(choices=[('FAR', 'Faritra'), ('FIK', 'Fikambanana Masina'), ('VAO', "Vaomieran'asa")], max_length=3)),
                ('fikambanana', models.CharField(max_length=50, unique=True)),
                ('mpiaro', models.CharField(max_length=50)),
                ('fankalazana', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Fikambanana',
            },
        ),
        migrations.CreateModel(
            name='Kristianina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anarana', models.CharField(max_length=100, unique=True)),
                ('nahaterahana', models.CharField(blank=True, default='', max_length=20)),
                ('nahatongavana', models.CharField(blank=True, default='', max_length=20)),
                ('batemy', models.CharField(blank=True, default='', max_length=20)),
                ('eokaristia', models.CharField(blank=True, default='', max_length=20)),
                ('fankaherezana', models.CharField(blank=True, default='', max_length=20)),
                ('mariazy', models.CharField(blank=True, default='', max_length=20)),
                ('asa', models.CharField(blank=True, default='', max_length=50)),
                ('fanamarihana', models.TextField(blank=True, default='')),
                ('tel', models.CharField(blank=True, default='', max_length=50)),
                ('mail', models.EmailField(blank=True, default='', max_length=254)),
                ('apv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paroasy.apv')),
            ],
            options={
                'verbose_name_plural': 'Kristianina',
            },
        ),
        migrations.CreateModel(
            name='Lohampianakaviana',
            fields=[
                ('kristianina', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='paroasy.kristianina')),
                ('karatra', models.CharField(blank=True, default='', max_length=20)),
                ('adiresy', models.CharField(blank=True, default='', max_length=100)),
                ('fanamarihana', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Lohampianakaviana',
            },
        ),
        migrations.CreateModel(
            name='Mpikambana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andraikitra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paroasy.andraikitra')),
                ('fikambanana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paroasy.fikambanana')),
                ('kristianina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paroasy.kristianina')),
            ],
            options={
                'verbose_name_plural': 'Mpikambana',
            },
        ),
        migrations.CreateModel(
            name='Tokantrano',
            fields=[
                ('kristianina', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='paroasy.kristianina')),
                ('laharana', models.IntegerField(default=10)),
                ('lohampianakaviana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paroasy.lohampianakaviana')),
            ],
            options={
                'verbose_name_plural': 'Tokantrano',
            },
        ),
        migrations.AddConstraint(
            model_name='mpikambana',
            constraint=models.UniqueConstraint(fields=('fikambanana', 'kristianina'), name='mpikambana'),
        ),
        migrations.AddField(
            model_name='bordereau',
            name='lohampianakaviana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paroasy.lohampianakaviana'),
        ),
        migrations.AddConstraint(
            model_name='bordereau',
            constraint=models.UniqueConstraint(fields=('numero', 'ligne'), name='bordereau'),
        ),
    ]
